project:
  type: website

website:
  title: ""
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Jonkman1/NSCR_Web
      - icon: website
        href: https://nscr.nl/en/
format:
  html:
    theme: theme.scss

editor: visual

